import logging
import warnings
from collections import OrderedDict
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm

from .provenance import check_header, read_header

__all__ = ['read_errors']

logger = logging.getLogger(__name__)


def read_errors(obs, eval_models, regions, seasons, eval_path):
    '''
    Read previously calculated error metrics from CSV files for model evaluation.

    This function reads error metrics from CSV files generated by the write_errors
    function. These metrics represent the performance of reference models against
    observations and are used to calculate relative performance indices for the
    models being evaluated.

    Parameters
    ----------
    obs : list
        List of variable objects representing observations
    eval_models : list
        List of Model objects used as reference for evaluation
    regions : list
        List of region objects defining geographical areas for evaluation
    seasons : list
        List of seasons to evaluate (e.g., ['DJF', 'MAM', 'JJA', 'SON'])
    eval_path : str
        Path to directory containing evaluation reference data

    Returns
    -------
    eval_error_mean : OrderedDict
        Mean error of the reference models, over the models that provide the
        variable, keyed by variable name, region name, level/depth and season

    Notes
    -----
    The function expects CSV files as written by write_errors: a header naming
    the observations and region masks, then columns for:
    - Variable name
    - Region name
    - Level/depth
    - Season
    - Absolute mean error value

    Each value is looked up by these four keys, so the order of the rows, and
    which other variables, regions and seasons a file contains, does not matter.
    A reference model without a variable is left out of the mean for that
    variable. A file that has the variable but lacks one of the requested
    regions, levels or seasons raises a KeyError that names the file and the row.

    A file without the header, or made with other observations than obs or
    other masks than those attached to regions, raises a ValueError: its
    errors are not comparable with this run.

    Examples
    --------
    >>> eval_error_mean = read_errors(obs, eval_models, regions, seasons, 'eval/ERA5/')

    AUTHORS:
    Jan Streffing               2022-11-30      Split off from main tool
    Jan Streffing               2026-09-28      Look up rows by key instead of walking the file
    Jan Streffing               2026-09-29      Check the header for observations and masks
    '''


    logger.info('Reading precalculated cmip6 field mean of errors from csv files')

    keys = [(var.name, region.name, depth, seas)
            for var in obs for region in regions for depth in var.depths for seas in seasons]
    collect = np.full((len(eval_models), len(keys)), np.nan)

    for i, eval_model in enumerate(tqdm(eval_models)):
        path = Path(eval_path) / (eval_model.name+'.csv')
        header, header_lines = read_header(path)
        check_header(path, header, obs, regions)
        table = pd.read_csv(path, delimiter=' ', skiprows=header_lines, dtype={'Variable': str, 'Region': str, 'Level': str, 'Season': str})
        table = table.set_index(['Variable', 'Region', 'Level', 'Season'])['AbsMeanError']
        if not table.index.is_unique:
            raise ValueError(str(path)+' has more than one row for the same variable, region, level and season')
        available = set(table.index.get_level_values('Variable'))
        for var in obs:
            logger.debug('%s %s %s', 'reading:' if var.name in available else 'filling:', eval_model.name, var.name)

        for j, key in enumerate(keys):
            if key[0] not in available: # This evaluation model does not provide the variable
                continue
            try:
                collect[i, j] = table.loc[key]
            except KeyError:
                raise KeyError(str(path)+' has '+key[0]+' but no row for region '+key[1]+', level '+key[2]
                               +', season '+key[3]) from None
            logger.debug('%s %s %s', eval_model.name, ' '.join(key), collect[i, j])

    # Ignoring non useful warning:
    # RuntimeWarning: Mean of empty slice, for variables no evaluation model provides
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        ensmean = np.nanmean(collect, axis=0)

    return OrderedDict(zip(keys, ensmean))
