def read_errors(obs, eval_models, regions, seasons, out_path, eval_path, verbose):
    '''
    Read previously calculated error metrics from CSV files for model evaluation.

    This function reads error metrics from CSV files generated by the write_errors
    function. These metrics represent the performance of reference models against
    observations and are used to calculate relative performance indices for the
    models being evaluated.

    Parameters
    ----------
    obs : list
        List of variable objects representing observations
    eval_models : list
        List of Model objects used as reference for evaluation
    regions : list
        List of region objects defining geographical areas for evaluation
    seasons : list
        List of seasons to evaluate (e.g., ['DJF', 'MAM', 'JJA', 'SON'])
    out_path : str
        Path to directory containing this run's output files
    eval_path : str
        Path to directory containing evaluation reference data
    verbose : bool
        Whether to print detailed information during execution

    Returns
    -------
    eval_error_mean : OrderedDict
        Mean error of the reference models, over the models that provide the
        variable, keyed by variable name, region name, level/depth and season

    Notes
    -----
    The function expects CSV files in a specific format with columns for:
    - Variable name
    - Region name
    - Level/depth
    - Season
    - Absolute mean error value

    Each value is looked up by these four keys, so the order of the rows, and
    which other variables, regions and seasons a file contains, does not matter.
    A reference model without a variable is left out of the mean for that
    variable. A file that has the variable but lacks one of the requested
    regions, levels or seasons raises a KeyError that names the file and the row.

    Examples
    --------
    >>> eval_error_mean = read_errors(obs, eval_models, regions, seasons,
    ...                              'output/', 'eval/ERA5/', verbose=True)

    AUTHORS:
    Jan Streffing               2022-11-30      Split off from main tool
    Jan Streffing               2026-09-28      Look up rows by key instead of walking the file
    '''

    import numpy as np
    import pandas as pd
    import warnings
    from collections import OrderedDict
    from tqdm import tqdm

    print('Reading precalculated cmip6 field mean of errors from csv files')

    keys = [(var.name, region.name, depth, seas)
            for var in obs for region in regions for depth in var.depths for seas in seasons]
    collect = np.full((len(eval_models), len(keys)), np.nan)

    for i, eval_model in enumerate(tqdm(eval_models)):
        path = eval_path+eval_model.name+'.csv'
        table = pd.read_csv(path, delimiter=' ', dtype={'Variable': str, 'Region': str, 'Level': str, 'Season': str})
        table = table.set_index(['Variable', 'Region', 'Level', 'Season'])['AbsMeanError']
        if not table.index.is_unique:
            raise ValueError(path+' has more than one row for the same variable, region, level and season')
        available = set(table.index.get_level_values('Variable'))
        if verbose:
            for var in obs:
                print('reading: ' if var.name in available else 'filling: ', eval_model.name, var.name)

        for j, key in enumerate(keys):
            if key[0] not in available: # This evaluation model does not provide the variable
                continue
            try:
                collect[i, j] = table.loc[key]
            except KeyError:
                raise KeyError(path+' has '+key[0]+' but no row for region '+key[1]+', level '+key[2]
                               +', season '+key[3]) from None
            if verbose:
                print(eval_model.name, *key, collect[i, j])

    # Ignoring non useful warning:
    # RuntimeWarning: Mean of empty slice, for variables no evaluation model provides
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        ensmean = np.nanmean(collect, axis=0)

    return OrderedDict(zip(keys, ensmean))
